/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.oned.EAN13Writer;

public class App {

    // Veja que esse metodo main encaminha uma exceção.
    public static void main(String[] args) throws Exception {
        int largura = 105;
        int altura = 5;

        String isbn = "9788576053576";

        EAN13Writer writer = new EAN13Writer();
        // Gera a matriz de bits para o formato EAN_13
        BitMatrix bitMatrix = writer.encode(isbn, BarcodeFormat.EAN_13, largura, 1);

        // Renderiza o código de barras usando blocos cheios █ e espaços em branco
        // https://www.unicodepedia.com/unicode/block-elements/2588/full-block/

        for (int i = 0; i < altura; i++) {
            for (int x = 0; x < bitMatrix.getWidth(); x++) {
                if (bitMatrix.get(x, 0)) {
                    System.out.print("\u2588");
                } else {
                    System.out.print(" ");
                }
            }
            System.out.println(); // Quebra de linha para a próxima camada da barra
        }
        System.out.println("ISBN-13: " + isbn);
    }

}