/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    /**
     * TODO: Matriz com asteriscos. Desenvolva um aplicativo Java que gere uma matriz quadrada de tamanho 9
     * e espalhe, de maneira aleatória, 10 asteriscos na matriz. Por fim, imprima na tela a matriz resultante.
     * Para as casas vazias da matriz, imprima o caractere ponto (.)
     *
     * @param args
     */
    public static void main(String[] args) {

    }
}
