/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Random;

public class App {

    /**
     * TODO: Matriz com asteriscos. Desenvolva um aplicativo Java que gere uma matriz quadrada de tamanho 9
     * e espalhe, de maneira aleatória, 10 asteriscos na matriz. Por fim, imprima na tela a matriz resultante.
     * Para as casas vazias da matriz, imprima o caractere ponto (.)
     *
     * @param args
     */
    public static void main(String[] args) {

        // Tamanho definido no enunciado
        final int tamanho = 9;

        // Cria matriz quadrada
        char[][] matriz = new char[tamanho][tamanho];

        Random random = new Random();
        int exemplo = random.nextInt(0,8);

        for (int i = 0; i < tamanho; i++) {
            for (int j = 0; j < tamanho; j++) {
                System.out.println(i + ":" + j);
            }
        }

    }
}
