/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.*;

public class App {

    /**
     * Matriz com asteriscos. Aplicativo Java que gera uma matriz quadrada de tamanho 9
     * e espalha, de maneira aleatória, 10 asteriscos na matriz. Por fim, imprime na tela a matriz resultante.
     * Para as casas vazias da matriz, imprime o caractere ponto (.)
     */
    public static void main(String[] args) {

        // Tamanhos definidos no enunciado
        final int tamanho = 9;
        final int quantidadeAsteriscos = 10;

        // Cria matriz quadrada
        char[][] matriz = new char[tamanho][tamanho];

        // Inicializa com '.'
        for (char[] linha : matriz) {
            Arrays.fill(linha, '.');
        }

        // Sorteia e insere os 10 asteriscos diretamente na matriz
        Random random = new Random();
        int inseridos = 0;

        while (inseridos < quantidadeAsteriscos) {
            int x = random.nextInt(tamanho);
            int y = random.nextInt(tamanho);

            if (matriz[x][y] != '*') {
                matriz[x][y] = '*';
                inseridos++;
            }
        }

        for (int i = 0; i < tamanho; i++) {
            for (int j = 0; j < tamanho; j++) {
                System.out.print(matriz[i][j] + " ");
            }
            System.out.println();
        }

    }
}
