/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {


    public static void main(String[] args) {
        Pessoa a = new Pessoa("Joao", "Joao@aluno.ifsc.edu.br");
        Pessoa b = new Pessoa("Paulo", "Paulo@aluno.ifsc.edu.br");

        System.out.println(a);
        System.out.println(b);
    }
}
