/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Disciplina disciplina = new Disciplina();
        disciplina.setName("POO");
        disciplina.setCargaHorariaEAD(20);
        disciplina.setCargaHorariaPresencial(80);
        disciplina.setCargaHorariaTotal(disciplina.getCargaHorariaEAD()+ disciplina.getCargaHorariaPresencial());

        System.out.println("Disciplina: "+disciplina.getName());
        System.out.println("Carga horária total: "+disciplina.getCargaHorariaTotal());
    }
}
