/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public String getGreeting(String nome) {
        return "------------- Hello "+nome+"! -------------";
    }

    public static void main(String[] args) {

        String nome = IO.readln("Entre com seu nome: ");

        System.out.println(new App().getGreeting(nome));

        int erros = 0;
        int acertos = 0;

        for (String aux: args){

            if (aux.equalsIgnoreCase("POO")){
                acertos++;
                if (acertos==1){
                    System.out.println("Acertou!");
                } else {
                    System.out.println("Acertou "+ acertos +" vezes!");
                }
            } else {
                erros++;
            }

        }
        System.out.println("-".repeat(40));
        System.out.println("Total de argumentos diferentes de POO: "+erros);
        System.out.println("-".repeat(40));
    }
}
