/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public String getGreeting() {
        return "------------- Hello World! -------------";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int erros = 0;
        int acertos = 0;

        for (String aux: args){

            if (aux.equalsIgnoreCase("POO")){
                acertos++;
                if (acertos==1){
                    System.out.println("Acertou!");
                } else {
                    System.out.println("Acertou "+ acertos +" vezes!");
                }
            } else {
                erros++;
            }

        }
        System.out.println("-".repeat(40));
        System.out.println("Total de argumentos diferentes de POO: "+erros);
        System.out.println("-".repeat(40));
    }
}
