/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    /**
     * TODO: Leitura de arquivo. Desenvolva um aplicativo Java que leia uma matriz, gerada pelo exercício anterior,
     * a partir de um arquivo texto e por meio do redirecionamento de entrada (uso do operador <). Para
     * cada casa da matriz em que não houver um asterisco, você deverá registrar o total de asteriscos
     * presentes nas casas adjacentes. Se não houverem asteriscos, então pode manter o caractere ponto
     * (.) na referida casa. Por fim, imprima a matriz resultante na tela.
     * IFSC – Campus São José Página 1
     * 💡 Dica
     * Apesar de ser solicitado imprimir pontos e asteriscos, você pode usar números inteiros para
     * representar a informação na memória. Por exemplo, o número 9 pode representar um asterisco
     * e o número 0 pode representar uma casa vazia.
     * @param args
     */
    public static void main(String[] args) {

    }
}
