/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {


    public static void main(String[] args) {
        Caneta canetaA = new Caneta("Azul", 50.0);
        System.out.println(canetaA);

        double[] coordenadaInicial = {1.1, 2.2};
        double[] coordenadaFinal = {2.1, 3.2};

        System.out.printf("Nível de tinta após desenhar: %.4f%n",canetaA.desenhar(coordenadaInicial,coordenadaFinal));
    }
}
