/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    void testMainOutput() {
        // Guarda a saída padrão original do console
        PrintStream originalOut = System.out;
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();

        try {
            // Redireciona System.out para capturar a impressão
            System.setOut(new PrintStream(outContent));

            // Executa o método main
            App.main(new String[]{});

            // Verifica se o texto impresso é exatamente o esperado (ignorando quebras de linha OS-dependent)
            String expected = "Olá mundo!" + System.lineSeparator();
            assertEquals(expected, outContent.toString());

        } finally {
            // Restaura a saída padrão original
            System.setOut(originalOut);
        }
    }
}
