/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void primeiraPessoaDeveTerId1() {
          Pessoa pessoa = new Pessoa("1","teste@teste1.com");
          assertEquals(pessoa.getId(),1);
    }

    @Test void segundaPessoaDeveTerId2() {
        Pessoa pessoa2 = new Pessoa("2","teste@teste2.com");
        assertEquals(pessoa2.getId(),2);
    }
}
