/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void primeiraPessoaDeveTerId1() {
        Pessoa pessoa1 = new Pessoa("1", "teste@teste1.com");
        assertEquals(1, pessoa1.getId());
    }

    @Test void deveIncrementarIdAosCriarPessoas() {
        Pessoa p1 = new Pessoa("1", "teste1@teste.com");
        Pessoa p2 = new Pessoa("2", "teste2@teste.com");

        assertEquals(p1.getId() + 1, p2.getId());
    }

    @Test void devePermitirSetarNome() {
        Pessoa pessoa3 = new Pessoa();
        pessoa3.setName("Joao");
        assertEquals("Joao", pessoa3.getName());
    }

    @Test void devePermitirSetarEmail() {
        Pessoa pessoa3 = new Pessoa();
        pessoa3.setEmail("Joao@gmail.com");
        assertEquals("Joao@gmail.com", pessoa3.getEmail()); // Corrigido de getName() para getEmail()
    }
}