/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Contador contador = new Contador();
        contador.setValorAtual(0);
        System.out.println("Valor atual do contador: "+contador.getValorAtual());
        System.out.println("Incrementando contador");
        contador.incrementarValorAtual();
        System.out.println("Valor atual do contador: "+contador.getValorAtual());
    }
}
