/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.entities.Aviao;

public class App {
    static void main(String[] args) {
        Aviao aviao = new Aviao(10, 10, 10, 8);
        aviao.ligarMotor(1);
    }
}
