/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Character personagem = new Character();

        personagem.setName("Jonas");
        personagem.setClasse("Guerreiro");
        personagem.setStr(19);
        personagem.setVit(15);
        personagem.setDex(12);
        personagem.setMag(3);

        System.out.printf("Personagem \033[1m%s\033[0m criado!%n",personagem.getName());
        System.out.printf("Força: %d%n", personagem.getStr());
        System.out.printf("Vitalidade: %d%n", personagem.getVit());
        System.out.printf("Destreza: %d%n", personagem.getDex());
        System.out.printf("Magia: %d%n", personagem.getMag());

    }
}
