/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import ads.poo.entities.Carro;
import ads.poo.entities.Motor;

public class App {

    public static void main(String[] args) {
        Motor m = new Motor(1, 2);
        Carro c = new Carro("WM",m);
    }
}
