/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {


        boolean entradaInvalida = args.length==0 || (args.length<2) && switch (args[0].toLowerCase()){
            case "triangulo", "losango", "retangulo" -> false;
            default -> true;
        };
        if (!entradaInvalida){

            int tamanho;
            int tamanho2Retangulo;

            String tipo = args[0].toLowerCase();
            tamanho = Integer.parseInt(args[1]);
            if (tipo.equals("retangulo")){
                tamanho2Retangulo=Integer.parseInt(args[1]);
                asciiArt(tamanho, tamanho2Retangulo);
            } else {
                asciiArt(tipo, tamanho);
            }

        } else {
            System.out.println("Informe argumentos válidos!");
        }

    }

    public static void asciiArt(String tipo, int tamanho) {
        if (tipo.equals("triangulo")){
            for (int i=1; i<=tamanho; i++){
                for (int j=1; j<=i; j++){
                    System.out.print("*");
                }
                System.out.println();
            }
        } else {
            int espacos = tamanho/2;
            // TODO Implementar impressao do losango
            System.out.println("TODO");
        }
    }
    public static void asciiArt(int tamanho, int tamanho2Retangulo) {
        String linhasInicialEFinal = "*".repeat(tamanho);
        String linhasCentrais = "*"+" ".repeat(tamanho-2)+"*";
        for (int i=1; i<=tamanho; i++){
            if (i==1 || i==tamanho){
                System.out.println(linhasInicialEFinal);

            } else {
                System.out.println(linhasCentrais);
            }
        }
    }
}
