/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.sql.SQLOutput;

public class App {

    public static void main(String[] args) {

        BatedeiraPlanetaria batedeira = new BatedeiraPlanetaria();
        String marca = "Phillips";
        System.out.println("Criando batereira da marca "+marca);
        batedeira.setMarca(marca);
        batedeira.setCargaAtual(0.0);
        System.out.println("Carga atual da batedeira: "+batedeira.getCargaAtual());
        double cargaAInserir = 10.5;

        System.out.printf("Inserindo %.2f Ml de carga%n",cargaAInserir);
        batedeira.inserirCarga(cargaAInserir);

        System.out.printf("Carga atual: %.2f%n", batedeira.getCargaAtual());

        double cargaARemover = 5.87;
        System.out.printf("Removendo %.2f Ml de carga%n",cargaARemover);
        batedeira.removerCarga(cargaARemover);

        System.out.printf("Carga atual: %.2f%n", batedeira.getCargaAtual());

        System.out.println("Ligando a batedeira: Batedeira ligada!");
        batedeira.setPower(true);
        batedeira.setVelocidade(1);
        System.out.println("Batedeira ligada, velocidade autal: "+batedeira.getVelocidade());

        System.out.println("Aumentando velocidade da batedeira..");
        batedeira.incrementarVelocidade();

        System.out.println("Velocidade atual: "+batedeira.getVelocidade());

    }
}
