/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Carro fusca = new Carro();

        System.out.println("Acelerando");
        fusca.acelerar(90);
        System.out.println("Acelerando");
        fusca.acelerar(20);

        System.out.printf("Velocidade atual: %.2f%n",fusca.getVelocidadeAtual());


        for (int i = 0; i<100; i++){
            double incremento = 10;
            fusca.acelerar(incremento);
        }


        System.out.printf("Velocidade atual: %.2f%n",fusca.getVelocidadeAtual());
    }
}
